SHELL := /bin/ksh

# TESTING THE SCRIPT
run_script_1_b:
	@echo "Run du script Question 1.b"
	cd python_virtual_environment; $$(poetry env info --path)/bin/python ../question_b.py -p EI -p EIRL -d 2020-02-01 -f 2020-09-01